### ISSUE TITLE
Update Lively to 0.1.0

### ISSUE THREAD

**Issue by nearengine** [synapsestudios/api-template#67]
### Acceptance Criteria
1. Lively configuration files are updated to new format
1. Lively is upgraded from 0.0.0 to 0.1.0 once design issues are resolved (see synapsestudios/lively#93)

**Comment by baohx2000** [comment]
Should probably wait for synapsestudios/lively#88 as well

**Comment by nearengine** [comment]
:boom: No longer applicable
